plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    implementation project(':azuki-core')
    implementation libs.jackson.module
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Azuki Listeners'
                description = 'Listeners that track Azuki events and perform common tasks'
            }
        }
    }
}

