plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    implementation project(":azuki-runner")
    implementation project(":azuki-verify:azuki-batch-api")

    implementation libs.kotlinx.serialization.json

    implementation libs.kotlin.reflect
    implementation libs.kotlinx.coroutines.core
    implementation libs.jackson.module
    implementation libs.kotlinx.html

    implementation libs.slf4j.api
    implementation libs.guava

    testImplementation libs.kotlin.test
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Azuki Scenario Orchestrator'
                description = 'Library to orchestrate verification by Azuki of a batch of scenarios'
            }
        }
    }
}
