plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    implementation project(":azuki-runner")
    implementation project(":azuki-verify:azuki-batch-api")

    implementation libs.kotlinx.serialization.json

    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "org.jetbrains.kotlin:kotlin-reflect"
    implementation libs.kotlinx.coroutines.core
    implementation libs.jackson.module
    implementation libs.kotlinx.html

    implementation libs.slf4j.api
    implementation group: 'com.google.guava', name: 'guava', version: '28.2-jre'

    testImplementation "org.jetbrains.kotlin:kotlin-test-junit"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Azuki Scenario Orchestrator'
                description = 'Library to orchestrate verification by Azuki of a batch of scenarios'
            }
        }
    }
}
