package com.anaplan.engineering.azuki.script.generation.runnable

import java.util.UUID
import kotlin.reflect.KClass

/**
 * Information about the name of a Kotlin definition (package, class, constant, and so on).
 *
 * This class hierarchy is mostly used for handling imports and references within runnable scenarios, and so is very
 * loosely defined with little internal resemblance to the JVM's concept of names.
 */
sealed class KotlinName: Comparable<KotlinName> {

    override fun toString() = fullName
    override fun compareTo(other: KotlinName) = fullName.compareTo(other.fullName)

    /**
     * The full (usually canonical) name, used for stringification and comparison.
     */
    abstract val fullName: String

    /**
     * The (often canonical) name that must be imported to bring the name into scope.
     */
    abstract val import: String

    /**
     * The package, if any, under which this name is located.
     */
    abstract val packageName: String

    /**
     * The (usually simple) name by which the identified object can be referred to when imported.
     */
    abstract val identifier: String

    val hasImport get() = import.isNotEmpty()
    val hasPackageName get() = packageName.isNotEmpty()
    val hasIdentifier get() = identifier.isNotEmpty()

    /**
     * Does this name work as an import for another definition name?
     */
    abstract fun satisfiesImport(other: KotlinName): Boolean

    /**
     * Creates a nested name.
     */
    infix fun dot(name: String): KotlinName = NestedName(this, name)

    companion object {

        /**
         * Creates a `KotlinName` directly from a Kotlin class reference.
         */
        fun KClass<*>.toClassName(): KotlinName = java.toClassName()

        /**
         * Creates a `KotlinName` directly from a Java class reference.
         */
        fun Class<*>.toClassName(): KotlinName = JavaClassName(this)

        /**
         * Creates a `KotlinName` directly from a package name and simple name.
         *
         * An attempt is made to sanitize any invalid characters, in case the name is autogenerated.
         */
        fun create(packageName: String, simpleName: String): KotlinName = BasicClassName(
            packageName.sanitized,
            simpleName.sanitized,
        )

        /**
         * Creates a `KotlinName` referencing a wildcard package import.
         *
         * An attempt is made to sanitize any invalid characters, in case the name is autogenerated.
         */
        fun wildcard(packageName: String): KotlinName = WildcardImport(
            packageName.sanitized,
        )

        /**
         * Create an arbitrary class name.
         */
        fun generateArbitrary(packageName: String) = create(packageName, "Generated_" + UUID.randomUUID().toString())

        private val String.sanitized get() = replace("-", "_")
    }
}

private class WildcardImport(override val packageName: String) : KotlinName() {

    override val fullName = "$packageName.*"
    override val import = fullName
    override val identifier = ""
    override fun satisfiesImport(other: KotlinName) = packageName == other.packageName
}

private class BasicClassName(override val packageName: String, simpleName: String) : KotlinName() {

    init {
        require(simpleName != "*") { "wildcard names should be created using `wildcard`" }
    }

    override val fullName = "$packageName.$simpleName"
    override val import = fullName
    override val identifier = simpleName
    override fun satisfiesImport(other: KotlinName) = import == other.import
}

private class JavaClassName(jClass: Class<*>) : KotlinName() {

    // TODO: detect and properly handle nesting?
    override val fullName: String = checkNotNull(jClass.canonicalName)
    override val import = fullName
    override val packageName: String = checkNotNull(jClass.packageName)
    override val identifier: String = checkNotNull(jClass.simpleName)
    override fun satisfiesImport(other: KotlinName) = import == other.import
}

private class NestedName(parent: KotlinName, child: String) : KotlinName() {

    init {
        require(parent.hasIdentifier) { "parent of a nested name must have an identifier" }
    }

    override val fullName = "${parent.fullName}.$child"
    override val import = parent.import
    override val packageName = parent.packageName
    override val identifier = "${parent.identifier}.$child"
    override fun satisfiesImport(other: KotlinName) = import == other.import
}
