package com.anaplan.engineering.azuki.script.generation.runnable

import com.anaplan.engineering.azuki.core.system.Behavior
import com.anaplan.engineering.azuki.core.system.FunctionalElement
import com.anaplan.engineering.azuki.script.generation.literal
import kotlin.reflect.KClass

/**
 * Information about a name that can be imported into a Kotlin script.
 */
sealed class Importable {

    /**
     * The (often canonical) name that must be imported to bring the name into scope.
     */
    abstract val import: String

    /**
     * The package, if any, under which this name is located.
     *
     * This is useful for working out which identifiers are affected by wildcard imports.
     */
    abstract val packageName: String

    /**
     * True if importing this identifier in a Kotlin situation would bring `other` into scope as well.
     *
     * For instance, a wildcard import on `foo.bar.*` can be used to import an identifier `foo.bar.baz`,
     * but an identifier `foo.bar.barbaz` cannot.
     */
    abstract infix fun canBeUsedToImport(other: Importable): Boolean

    companion object {

        /**
         * Creates a qualified identifier referencing a wildcard package import.
         *
         * An attempt is made to sanitize any invalid characters, in case the name is autogenerated.
         */
        fun wildcard(packageName: String): Importable = WildcardImport(packageName.sanitizeForIdentifiers)
    }
}

/**
 * The fully-qualified identifier of a Kotlin definition (package, class, constant, and so on).
 *
 * This class hierarchy is mostly used for handling imports and references within runnable scenarios, and so is very
 * loosely defined with little internal resemblance to the JVM's concept of names.
 */
sealed class QualifiedIdentifier : Importable() {

    /**
     * The unqualified part of the identifier, by which the identified object can be referred to when imported.
     */
    abstract val identifier: String

    /**
     * Creates a nested identifier.
     *
     * A nested identifier is imported in the same way as its parent, but has its identifier qualified by that
     * of the parent.
     */
    infix fun dot(name: String): QualifiedIdentifier = NestedIdentifier(this, name)

    companion object {

        /**
         * Creates a qualified identifier directly from a Kotlin class reference.
         */
        fun KClass<*>.toQualifiedIdentifier(): QualifiedIdentifier = java.toQualifiedIdentifier()

        /**
         * Creates a qualified identifier directly from a Java class reference.
         */
        fun Class<*>.toQualifiedIdentifier(): QualifiedIdentifier = JavaClassName(this)

        /**
         * Creates a qualified identifier directly from a package name and simple name.
         *
         * An attempt is made to sanitize any invalid characters, in case the name is autogenerated.
         */
        fun create(packageName: String, simpleName: String): QualifiedIdentifier = BasicQualifiedIdentifier(
            packageName.sanitizeForIdentifiers,
            simpleName.sanitizeForIdentifiers,
        )
    }
}

private class WildcardImport(override val packageName: String) : Importable() {

    override fun toString() = import
    override val import = "$packageName.*"

    /**
     * Wildcard imports can be used as imports for anything with the same package name.
     */
    override fun canBeUsedToImport(other: Importable) = packageName == other.packageName
}

private class BasicQualifiedIdentifier(override val packageName: String, simpleName: String) : QualifiedIdentifier() {

    override fun toString() = import
    override val import = "$packageName.$simpleName"
    override val identifier = simpleName
    override fun canBeUsedToImport(other: Importable) = import == other.import
}

private class JavaClassName(jClass: Class<*>) : QualifiedIdentifier() {

    // TODO: detect and properly handle nesting?
    override fun toString() = import
    override val import: String = checkNotNull(jClass.canonicalName)
    override val packageName: String = checkNotNull(jClass.packageName)
    override val identifier: String = checkNotNull(jClass.simpleName)
    override fun canBeUsedToImport(other: Importable) = import == other.import
}

private class NestedIdentifier(parent: QualifiedIdentifier, child: String) : QualifiedIdentifier() {

    init {
        require(parent.identifier.isNotEmpty()) { "parent of a nested name must have an identifier" }
    }

    private val fullName = "$parent.$child"
    override fun toString() = fullName

    override val import = parent.import
    override val packageName = parent.packageName
    override val identifier = "${parent.identifier}.$child"
    override fun canBeUsedToImport(other: Importable) = import == other.import
}

private val String.sanitizeForIdentifiers get(): String {
    require(isNotBlank()) { "identifier strings cannot be blank" }
    require(!contains("*")) { "wildcards not allowed here" }
    // We're more tolerant of the following, which are less likely to be errors in using QualifiedIdentifier
    // and more likely to be passing things in from other parts of a verification-generation setup verbatim
    return replace("-", "_")
}

/**
 * Ordered set of imports with support for automatically tracking imports for referenced identifiers.
 */
class ImportSet(vararg initialImports: Importable) {

    /**
     * Gets the sorted imports tracked by this set.
     */
    val imports get() = _imports.map { it.import }.sorted()

    private var _imports = initialImports.toMutableList()

    /**
     * Adds multiple imports, if they aren't already tracked.
     */
    operator fun plusAssign(imports: Collection<Importable>) {
        imports.forEach { this += it }
    }

    /**
     * Adds an import, if it isn't already tracked.
     */
    operator fun plusAssign(importable: Importable) {
        if (_imports.none { it canBeUsedToImport importable }) {
            _imports.add(importable)
        }
    }
}

/**
 * Performs reverse mapping from Kotlin identifiers of Azuki concepts (such as behaviors, functional elements, and
 * implementation names) to their definitions, allowing the former to be substituted for the latter during script
 * generation.
 *
 * This is an optional cosmetic step; most use cases can get away with using the default 'Empty' mapper.
 */
interface IdentifierMapper {

    /**
     * Partial map from behavioral constants to their definitions (captured as qualified identifiers).
     *
     * This is used to prettify BEH annotations.
     *
     * It should be the case that, for each `(key, value)` pair mapped by this function, if `value` is present in
     * the classpath then it evaluates to `key`.
     */
    fun getBehaviorIdentifier(beh: Behavior): QualifiedIdentifier? = null

    /**
     * Partial map from functional element constants to their definitions (captured as qualified identifiers).
     *
     * This is used to prettify BEH annotations.
     *
     * It should be the case that, for each `(key, value)` pair mapped by this function, if `value` is present in
     * the classpath then it evaluates to `key`.
     */
    fun getFunctionalElementIdentifier(fe: FunctionalElement): QualifiedIdentifier? = null

    /**
     * Partial map from implementation name values to their definitions (captured as qualified identifiers).
     *
     * This is used to prettify annotations that rely on implementation names.
     *
     * It should be the case that, for each `(key, value)` pair mapped by this function, if `value` is present in
     * the classpath then it evaluates to `key`.
     */
    fun getImplementationIdentifier(impl: String): QualifiedIdentifier? = null

    /**
     * An identifier mapper that maps nothing.
     */
    object Empty: IdentifierMapper
}

/**
 * Holds information about how to resolve Azuki concepts (such as behaviors, functional elements, and implementations)
 * to identifiers, and associate identifiers to their imports.
 */
class IdentifierContext(
    /**
     * Tracks imports that have been referenced by a script.
     */
    val imports: ImportSet,
    /**
     * Maps Azuki concepts to their definitions (captured as qualified identifiers).
     */
    val mapper: IdentifierMapper,
) {

    /**
     * Tries to reverse-lookup a behavior number as a constant identifier, and import it if successful.
     * If there is no known identifier, the behavior will be escaped as a decimal integer literal.
     */
    fun behavior(beh: Behavior) =
        mapper.getBehaviorIdentifier(beh)?.let(this::identifier) ?: beh.toString()

    /**
     * Tries to reverse-lookup a functional element number as a constant identifier, and import it if successful.
     * If there is no known identifier, the functional element will be escaped as a decimal integer literal.
     */
    fun functionalElement(fe: FunctionalElement) =
        mapper.getFunctionalElementIdentifier(fe)?.let(this::identifier) ?: fe.toString()

    /**
     * Tries to reverse-lookup a string implementation name as a constant identifier, and import it if successful.
     * If there is no known identifier, the implementation string will be escaped as a string literal.
     */
    fun implementation(impl: String) =
        mapper.getImplementationIdentifier(impl)?.let(this::identifier) ?: impl.literal

    /**
     * Retrieves the identifier of the name, adding an import for it to the import set if needed.
     */
    fun identifier(name: QualifiedIdentifier): String {
        imports += name
        return name.identifier
    }
}
