package com.anaplan.engineering.azuki.script.generation.runnable

import kotlin.reflect.KClass

/**
 * Information about a name that can be imported into a Kotlin script.
 */
sealed class Importable {

    /**
     * The (often canonical) name that must be imported to bring the name into scope.
     */
    abstract val import: String

    /**
     * The package, if any, under which this name is located.
     *
     * This is useful for working out which identifiers are affected by wildcard imports.
     */
    abstract val packageName: String

    /**
     * True if importing this identifier in a Kotlin situation would bring `other` into scope as well.
     *
     * For instance, a wildcard import on `foo.bar.*` can be used to import an identifier `foo.bar.baz`,
     * but an identifier `foo.bar.barbaz` cannot.
     */
    abstract infix fun canBeUsedToImport(other: Importable): Boolean

    companion object {

        /**
         * Creates a qualified identifier referencing a wildcard package import.
         *
         * An attempt is made to sanitize any invalid characters, in case the name is autogenerated.
         */
        fun wildcard(packageName: String): Importable = WildcardName(packageName.sanitizeForQualifiedName)
    }
}

/**
 * The fully-qualified identifier of a Kotlin definition (package, class, constant, and so on).
 *
 * This class hierarchy is mostly used for handling imports and references within runnable scenarios, and so is very
 * loosely defined with little internal resemblance to the JVM's concept of names.
 */
sealed class QualifiedName : Importable() {

    /**
     * The unqualified part of the name, by which the identified object can be referred to when imported.
     */
    abstract val simpleName: String

    /**
     * Creates a nested identifier.
     *
     * A nested identifier is imported in the same way as its parent, but has its identifier qualified by that
     * of the parent.
     */
    infix fun dot(name: String): QualifiedName = NestedName(this, name)

    companion object {

        /**
         * Creates a qualified identifier directly from a Kotlin class reference.
         */
        fun KClass<*>.asQualifiedName(): QualifiedName = java.asQualifiedName()

        /**
         * Creates a qualified identifier directly from a Java class reference.
         */
        fun Class<*>.asQualifiedName(): QualifiedName = JavaClassName(this)

        /**
         * Creates a qualified identifier directly from a package name and simple name.
         *
         * We make a basic attempt to sanitize or reject any invalid characters.  For instance, whitespace is rejected
         * outright, and hyphens are replaced with underscores.
         */
        fun create(packageName: String, simpleName: String): QualifiedName = BasicQualifiedName(
            packageName.sanitizeForQualifiedName,
            simpleName.sanitizeForQualifiedName,
        )
    }
}

private class WildcardName(override val packageName: String) : Importable() {

    init {
        packageName.checkValidForQualifiedName()
    }

    override fun toString() = import
    override val import = "$packageName.*"

    /**
     * Wildcard imports can be used as imports for anything with the same package name.
     */
    override fun canBeUsedToImport(other: Importable) = packageName == other.packageName
}

private class BasicQualifiedName(override val packageName: String, override val simpleName: String) : QualifiedName() {

    init {
        packageName.checkValidForQualifiedName()
        simpleName.checkValidForQualifiedName()
    }

    override fun toString() = import
    override val import = "$packageName.$simpleName"
    override fun canBeUsedToImport(other: Importable) = import == other.import
}

private class JavaClassName(jClass: Class<*>) : QualifiedName() {

    // TODO: detect and properly handle nesting?
    override fun toString() = import
    override val import: String = checkNotNull(jClass.canonicalName)
    override val packageName: String = checkNotNull(jClass.packageName)
    override val simpleName: String = checkNotNull(jClass.simpleName)
    override fun canBeUsedToImport(other: Importable) = import == other.import
}

private class NestedName(parent: QualifiedName, child: String) : QualifiedName() {

    init {
        // assume inductively that `parent` is valid
        require(parent.simpleName.isNotEmpty()) { "parent of a nested name must have a simple name" }
        child.checkValidForQualifiedName()
    }

    private val fullName = "$parent.$child"
    override fun toString() = fullName

    override val import = parent.import
    override val packageName = parent.packageName
    override val simpleName = "${parent.simpleName}.$child"
    override fun canBeUsedToImport(other: Importable) = import == other.import
}

private val String.sanitizeForQualifiedName get() =
    // We're more tolerant of the following, which are less likely to be errors in using QualifiedName
    // and more likely to be passing things in from other parts of a verification-generation setup verbatim
    replace("-", "_")

private fun String.checkValidForQualifiedName() {
    // NOTE: this is not exhaustive but tries to catch out the most likely issues
    require(isNotBlank()) { "parts of names cannot be blank" }
    require(!contains("*")) { "wildcards not allowed here" }
    require(!contains("-")) { "hyphens not allowed here" }
}

/**
 * Ordered set of imports with support for automatically tracking imports for referenced identifiers.
 */
class ImportSet(vararg initialImports: Importable) : Collection<Importable> {

    private var _imports = mutableListOf<Importable>()

    init {
        // Make sure we do filtering on the initial imports
        this += initialImports.toList()
    }

    /**
     * Gets the sorted imports tracked by this set.
     */
    val imports get() = _imports.map { it.import }.sorted()

    /**
     * Adds multiple imports, if they aren't already tracked.
     */
    operator fun plusAssign(imports: Collection<Importable>) {
        imports.forEach { this += it }
    }

    /**
     * Adds an import, if it isn't already tracked.
     */
    operator fun plusAssign(importable: Importable) {
        // Don't add if the import is already tracked...
        if (_imports.none { it canBeUsedToImport importable }) {
            // ...and remove anything that is a more narrow equivalent of this import
            _imports.removeAll { importable canBeUsedToImport it }
            _imports.add(importable)
        }
    }

    override val size get() = _imports.size
    override fun contains(element: Importable) = _imports.contains(element)
    override fun containsAll(elements: Collection<Importable>) = _imports.containsAll(elements)
    override fun isEmpty() = _imports.isEmpty()
    override fun iterator() = _imports.sortedBy { it.import }.iterator()
}
