include(
    "azuki-core",
    "azuki-vdm",
    "azuki-declaration",
    "azuki-listeners",
    "azuki-result-reporter",
    "azuki-runner",
    "azuki-script-formatter",
    "azuki-script-generation",
    "azuki-verify:azuki-batch-api",
    "azuki-verify:azuki-batch-guided",
    "azuki-verify:azuki-orchestrator",
    "azuki-verify:azuki-generation-utilities",
    "packaging-tools",
    "tictactoe:dsl",
    "tictactoe:adapter-api",
    "tictactoe:adapter-declaration",
    "tictactoe:adapter-script-generation",
    "tictactoe:adapter-vdm",
    "tictactoe:adapter-kazuki",
    "tictactoe:kazuki",
    "tictactoe:implementation",
    "tictactoe:implementation-v1",
    "tictactoe:implementation-v2",
    "tictactoe:adapter-implementation",
    "tictactoe:eacs",
    "tictactoe:script-runner",
    "graphs:dsl",
    "graphs:adapter-api",
    "graphs:adapter-declaration",
    "graphs:adapter-apache",
    "graphs:adapter-guava",
    "graphs:adapter-jgrapht",
    "graphs:adapter-jung",
    "graphs:adapter-script-generation",
    "graphs:eacs",
    "graphs:tests",
    "graphs:script-runner",
    "graphs:verification-runner",
    'right-of-way',
    'right-of-way:adapter-api',
    'right-of-way:adapter-declaration',
    'right-of-way:adapter-implementation',
    'right-of-way:adapter-kazuki',
//    'right-of-way:adapter-vdm',
    'right-of-way:dsl',
    'right-of-way:kauzki',
//    'right-of-way:eacs',
    'right-of-way:implementation',
    'right-of-way:implementation-V1',
)
includeBuild("build-conventions")
includeBuild("vdm-animation")
includeBuild("vdm-stub-generator")
includeBuild("azuki-platform")
