include(
    "azuki-core",
    "azuki-vdm",
    "azuki-declaration",
    "azuki-listeners",
    "azuki-result-reporter",
    "azuki-runner",
    "azuki-script-formatter",
    "azuki-script-generation",
    "azuki-verify:azuki-batch-api",
    "azuki-verify:azuki-batch-guided",
    "azuki-verify:azuki-orchestrator",
    "azuki-verify:azuki-generation-utilities",
    "examples:tictactoe:dsl",
    "examples:tictactoe:adapter-api",
    "examples:tictactoe:adapter-declaration",
    "examples:tictactoe:adapter-script-generation",
    "examples:tictactoe:adapter-vdm",
    "examples:tictactoe:adapter-kazuki",
    "examples:tictactoe:kazuki",
    "examples:tictactoe:implementation",
    "examples:tictactoe:implementation-v1",
    "examples:tictactoe:implementation-v2",
    "examples:tictactoe:adapter-implementation",
    "examples:tictactoe:eacs",
    "examples:tictactoe:script-runner",
    "examples:graphs:dsl",
    "examples:graphs:adapter-api",
    "examples:graphs:adapter-declaration",
    "examples:graphs:adapter-apache",
    "examples:graphs:adapter-guava",
    "examples:graphs:adapter-jgrapht",
    "examples:graphs:adapter-jung",
    "examples:graphs:adapter-script-generation",
    "examples:graphs:eacs",
    "examples:graphs:tests",
    "examples:graphs:script-runner",
    "examples:graphs:verification-runner",
    'examples:right-of-way:adapter-api',
    'examples:right-of-way:adapter-declaration',
    'examples:right-of-way:adapter-script-generation',
    'examples:right-of-way:adapter-vdm',
    'examples:right-of-way:adapter-kazuki',
    'examples:right-of-way:adapter-implementation',
    'examples:right-of-way:dsl',
    'examples:right-of-way:kazuki',
    'examples:right-of-way:script-runner',
    'examples:right-of-way:eacs',
    'examples:right-of-way:implementation',
    'examples:right-of-way:implementation-V1',
    "mondex:dsl",
    "mondex:adapter-api",
    "mondex:eacs",
)
includeBuild("build-conventions")
includeBuild("vdm-animation")
includeBuild("vdm-stub-generator")
includeBuild("azuki-platform")

include 'mondex:adapter-api'
