package com.anaplan.engineering.azuki.reflect.metadata

/**
 * Information about a name that can be imported into a Kotlin script.
 */
sealed class Importable {

    /**
     * The (often canonical) name that must be imported to bring the name into scope.
     */
    abstract val import: String

    /**
     * The package, if any, under which this name is located.
     *
     * This is useful for working out which identifiers are affected by wildcard imports.
     */
    abstract val packageName: String

    /**
     * True if importing this identifier in a Kotlin situation would bring `other` into scope as well.
     *
     * For instance, a wildcard import on `foo.bar.*` can be used to import an identifier `foo.bar.baz`,
     * but an identifier `foo.bar.barbaz` cannot.
     */
    abstract infix fun canBeUsedToImport(other: Importable): Boolean

    companion object {

        /**
         * Creates a qualified identifier referencing a wildcard package import.
         *
         * An attempt is made to sanitize any invalid characters, in case the name is autogenerated.
         */
        fun wildcard(packageName: String): Importable = WildcardName(packageName.sanitizedForQualifiedName)
    }
}

private class WildcardName(override val packageName: String) : Importable() {

    init {
        packageName.checkValidForQualifiedName()
    }

    override fun toString() = import
    override val import = "$packageName.*"

    /**
     * Wildcard imports can be used as imports for anything with the same package name.
     */
    override fun canBeUsedToImport(other: Importable) = packageName == other.packageName
}
