plugins {
    id 'azuki.kotlin-conventions'
    id "com.anaplan.engineering.vdm-stub-generator"
}

configurations {
    sampleImpl
    vdm
    kazuki
}

dependencies {
    implementation project(":right-of-way:adapter-script-generation")
    implementation project(":azuki-runner")
    implementation project(":azuki-verify:azuki-generation-utilities")

    implementation libs.clikt.jvm
    implementation libs.kotlin.reflect
    implementation libs.jackson.module
    implementation libs.slf4j.api
    implementation libs.log4j.core
    runtimeOnly libs.slf4j.impl

    //TODO LF: waht these qualified projects do here?
    sampleImpl project(":right-of-way:adapter-implementation")
    sampleImpl project(":right-of-way:implementation-V1")

    vdm project(":right-of-way:adapter-vdm")

    kazuki project(":right-of-way:adapter-kazuki")
    kazuki project(":right-of-way:kazuki")
}

task sampleImplClasspathJar(type: Jar) {
    dependsOn configurations.sampleImpl
    archiveBaseName = 'SampleImpl'
    manifest {
        attributes(
            "Class-Path": configurations.sampleImpl.collect { it.absolutePath }.join(' '))
    }
}

task kazukiClasspathJar(type: Jar) {
    dependsOn configurations.kazuki
    archiveBaseName = 'Kazuki'
    manifest {
        attributes(
            "Class-Path": configurations.kazuki.collect { it.absolutePath }.join(' '))
    }
}

task vdmClasspathJar(type: Jar) {
    dependsOn configurations.vdm
    archiveBaseName = 'VDM'
    manifest {
        attributes(
            "Class-Path": configurations.vdm.collect { it.absolutePath }.join(' '))
    }
}

ext {
    scenarioFile = providers.gradleProperty("scenarioFile").getOrElse("script.scn")
    oracleScenarioFile = providers.gradleProperty("oracleScenarioFile").getOrElse("oracle_script.scn")
}

task runScript(type: JavaExec) {
    dependsOn vdmClasspathJar
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.anaplan.engineering.azuki.rightofway.scriptrunner.RightOfWayScenarioScriptRunnerKt'
    jvmArgs '-Xmx4g', "--add-opens=java.base/java.nio=ALL-UNNAMED"
    args = [
        "-d", file("build/run${System.currentTimeMillis()}").absolutePath,
        "-v", file("build/verified").absolutePath,
        "-u", file("build/unverified").absolutePath,
        "-i", file("config/imports").absolutePath,
        "-t", "VDM",
        file(scenarioFile).absolutePath,
    ]
    def instanceJars = [
        vdmClasspathJar.archiveFile.get().asFile.absolutePath,
    ]
    systemProperties = [
        "com.anaplan.engineering.azuki.implementation.instance.jars": instanceJars.join(","),
    ]
}

task runOracleScript(type: JavaExec) {
    dependsOn sampleImplClasspathJar
    dependsOn kazukiClasspathJar
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.anaplan.engineering.azuki.rightofway.scriptrunner.RightOfWayScenarioScriptRunnerKt'
    jvmArgs '-Xmx4g', "--add-opens=java.base/java.nio=ALL-UNNAMED"
    args = [
        "-d", file("build/run${System.currentTimeMillis()}").absolutePath,
        "-v", file("build/verified").absolutePath,
        "-u", file("build/unverified").absolutePath,
        "-i", file("config/imports").absolutePath,
        "-t", "SampleImpl",
        "-o", "Kazuki",
        file(oracleScenarioFile).absolutePath,
    ]
    def instanceJars = [
        sampleImplClasspathJar.archiveFile.get().asFile.absolutePath,
        kazukiClasspathJar.archiveFile.get().asFile.absolutePath,
    ]
    systemProperties = [
        "com.anaplan.engineering.azuki.implementation.instance.jars": instanceJars.join(','),
    ]
}
