plugins {
    id 'azuki.common-conventions'
    alias(libs.plugins.kotlin)
    id 'com.google.devtools.ksp' version("2.1.21-2.0.1")
}

dependencies {
    implementation platform(libs.kotlin.bom)
    implementation libs.kotlin.reflect
    api libs.kazuki.toolkit
    ksp libs.kazuki.ksp
    implementation libs.kotlin.test
    implementation libs.slf4j.api
    testRuntimeOnly libs.slf4j.impl
}

ksp {
    arg("com.anaplan.engineering.kazuki.compile.debug.level", "INFO")
    useKsp2 = false
}
