plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    api project(":azuki-core")
    implementation libs.slf4j.api
    runtimeOnly libs.jna
    runtimeOnly libs.slf4j.impl
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Azuki Runner'
                description = 'Standalone tools to run Azuki scenarios'
            }
        }
    }
}

