plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    // 1.5.0+ are based on Kotlin 2.1, and would require the script parser to be pinned to the 2.1 version
    implementation 'com.pinterest.ktlint:ktlint-rule-engine:1.4.1'
    implementation 'com.pinterest.ktlint:ktlint-ruleset-standard:1.4.1'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Azuki Script Formatter'
                description = 'Tools to assist with formatting Azuki scenario scripts'
            }
        }
    }
}
