plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    implementation libs.ktlint.ruleEngine
    implementation libs.ktlint.rulesetStandard
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Azuki Script Formatter'
                description = 'Tools to assist with formatting Azuki scenario scripts'
            }
        }
    }
}
