plugins {
    id 'azuki.kotlin-conventions'
}

dependencies {
    api project(":examples:tictactoe:adapter-declaration")
    compileOnly project(":examples:tictactoe:implementation")
    implementation libs.slf4j.api
    implementation libs.kotlinx.serialization.json
    implementation libs.jackson.module
}
