plugins {
    id 'azuki.kotlin-conventions'
}

dependencies {
    //TODO: impl shouldn't know about the adapter?
    //api project(":right-of-way:adapter-api")
    implementation libs.kotlin.test
    implementation libs.kotlinx.serialization.json
    implementation libs.jackson.module
    implementation libs.slf4j.api
    testRuntimeOnly libs.slf4j.impl
}
