plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    api project(":azuki-core")
    api "com.anaplan.engineering:vdm-animation-api:$version"
    implementation libs.jackson.module
    runtimeOnly "com.anaplan.engineering:vdm-animation-overture:$version"
//    runtimeOnly "com.anaplan.engineering:vdm-animation-vdmj:$version"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Azuki VDM tools'
                description = 'Tools for adapting to VDM when using the Azuki framework for behaviour driven specification'
            }
        }
    }
}
