package com.anaplan.engineering.azuki.mondex.adapter.api

import com.anaplan.engineering.azuki.core.system.Action
import com.anaplan.engineering.azuki.core.system.ActionFactory
import com.anaplan.engineering.azuki.core.system.ParallelActionFactory
import com.anaplan.engineering.azuki.core.system.UnsupportedAction
import org.slf4j.LoggerFactory

interface MondexActionFactory<out A: Action > : ActionFactory, ParallelActionFactory<A> {
    val purse: PurseActionFactory
    val world: WorldActionFactory
    val protocol: ProtocolActionFactory
}

interface PurseActionFactory {
    fun create(purseName: String, purse: Purse): Action
}

// Ch.3 top-level protocol operations, meant for the `whenever` section
interface ProtocolActionFactory {
    fun transferOkay(td: TransferDetails): Action = unsupportedAction()
    fun transferLost(td: TransferDetails): Action = unsupportedAction()
    fun ignore(): Action = unsupportedAction()
}

// Mondex world creation operations, not explicitly described in PRG126, meant for `given` section
interface WorldActionFactory {
    fun createAbWorld(name: String, purses: Map<String, AbPurse>) = unsupportedAction()
    fun createConWorld(name: String, purses: Map<String, ConPurse>) = unsupportedAction()
}

private val Log = LoggerFactory.getLogger(MondexActionFactory::class.java)

// Helpful logging of unsupported caller
private fun unsupportedAction(): Action {
    val caller = Thread.currentThread().stackTrace[3]
    Log.warn("UnsupportedAction generated by ${caller.className}.${caller.methodName}")
    return UnsupportedAction
}
