plugins {
    id 'azuki.kotlin-conventions'
}

dependencies {
    //No need; api project import is transitive
    //api project(":right-of-way:adapter-api")
    api project(":right-of-way:adapter-declaration")
    compileOnly project(":right-of-way:implementation")
    implementation libs.slf4j.api
    implementation libs.jackson.module
}
