plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    implementation project(":azuki-verify:azuki-batch-api")

    implementation libs.kotlin.reflect

    implementation libs.slf4j.api
    implementation libs.guava
    implementation libs.jackson.module
    implementation libs.kotlinx.html


    implementation libs.jna

    testImplementation libs.kotlin.test
    testImplementation libs.mockk
    testRuntimeOnly libs.slf4j.impl

}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Azuki Scenario Guided Batch'
                description = 'Library to construct a batch of guided scenarios to verify with Azuki'
            }
        }
    }
}
