plugins {
    id 'maven-publish'
    id 'signing'
}


publishing {
    repositories {
        maven {
            url 'https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/'
            credentials {
                username findProperty("centralPortalUsername")
                password findProperty("centralPortalPassword")
            }
        }
    }
}

