plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'azuki.common-conventions'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation platform(libs.kotlin.bom)
    implementation libs.kotlin.reflect

    testImplementation libs.kotlin.test
}
