#!/bin/bash

# This script will upload the contained artifacts to the Maven Central staging repository

# To run this script you will need to have ossrhUsername and ossrhPassword properties defined in your user gradle.properties with your credentials for Nexus

# Note that, using a gradle task similar to publishAllToMavenLocal does not work as it tries to upload the same artifact more than once

set -e

VERSION="$1"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR="$SCRIPT_DIR/.."
ANIMATION_DIR="$PROJECT_DIR/vdm-animation"
STUB_DIR="$PROJECT_DIR/vdm-stub-generator"
GRADLEW="$PROJECT_DIR/gradlew"

echo "Publishing VDM animation"

cd "$ANIMATION_DIR"
"$GRADLEW" publish -Pversion="$VERSION"

echo "Publishing stub generator"

cd "$STUB_DIR"
"$GRADLEW" publish publishPlugins -Pversion="$VERSION"

echo "Publishing Azuki"

cd "$PROJECT_DIR"
"$GRADLEW" publish -Pversion="$VERSION"

TAG=""v$VERSION""
git tag -a $TAG -m "Release $TAG"
git push origin "$TAG"
