plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    implementation project(":azuki-script-generation")
    implementation libs.slf4j.api
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Azuki Generation Utilities for Verification'
                description = 'Library of utilities for generating verifiable scenarios from oracle scenarios'
            }
        }
    }
}
