plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-test-junit'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin:2.12.5'
    implementation 'org.semver4j:semver4j:5.2.2'
    implementation 'org.slf4j:slf4j-api:1.7.36'

    implementation 'org.jetbrains.kotlin:kotlin-compiler-embeddable'
    implementation 'org.jetbrains.kotlin:kotlin-scripting-common'
    implementation 'org.jetbrains.kotlin:kotlin-scripting-jvm'
    implementation 'org.jetbrains.kotlin:kotlin-scripting-jvm-host'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Azuki'
                description = 'The core library of the Azuki framework for behaviour driven specification'
            }
        }
    }
}

