package com.anaplan.engineering.azuki.examples.mondex.adaption.intra.api

import com.anaplan.engineering.azuki.core.system.Action
import com.anaplan.engineering.azuki.core.system.ActionFactory
import com.anaplan.engineering.azuki.core.system.UnsupportedAction
import org.slf4j.LoggerFactory
import kotlin.jvm.java


interface IntraWorldActionFactory<out A : Action> : ActionFactory {
    val purse: PurseActionFactory
    val world: WorldActionFactory
    val transfer: TransferActionFactory
}

interface PurseActionFactory {
    fun create(purseName: String, balance: Int) = unsupportedAction()
}

interface WorldActionFactory {
    fun create(worldName: String) = unsupportedAction()
    fun addPurse(worldName: String, purseName: String) = unsupportedAction()
    fun addTransfer(worldName: String, transferName: String) = unsupportedAction()
}

interface TransferActionFactory {
    fun create(transferName: String, fromPurse: String, toPurse: String, amount: Int) = unsupportedAction()
    fun makeATransfer(from: String, to: String, amount: Int, successful: Boolean) = unsupportedAction()
    fun request(transferName: String) = unsupportedAction()
    fun send(transferName: String) = unsupportedAction()
    fun acknowledge(transferName: String) = unsupportedAction()
    fun abort(transferName: String) = unsupportedAction()
}


fun unsupportedAction(): Action {
    val caller = Thread.currentThread().stackTrace[3]
    Log.warn("UnsupportedAction generated by ${caller.className}.${caller.methodName}")
    return UnsupportedAction
}

private val Log = LoggerFactory.getLogger(IntraWorldActionFactory::class.java)
