package com.anaplan.engineering.azuki.examples.mondex.adaption.intra.api

import com.anaplan.engineering.azuki.core.system.Check
import com.anaplan.engineering.azuki.core.system.CheckFactory
import com.anaplan.engineering.azuki.core.system.UnsupportedCheck
import org.slf4j.LoggerFactory
import kotlin.jvm.java

interface IntraWorldCheckFactory : CheckFactory {
    val purse: PurseCheckFactory
    val world: WorldCheckFactory
}

interface PurseCheckFactory {
    fun hasBalance(purseName: String, balance: Int) = unsupportedCheck()
    fun hasLost(purseName: String, lost: Int) = unsupportedCheck()
    fun exLogContains(purseName: String, transferName: String) = unsupportedCheck()
}

interface WorldCheckFactory {
    fun hasTotalValue(worldName: String, value: Int) = unsupportedCheck()
    fun hasTotalBalance(worldName: String, balance: Int) = unsupportedCheck()
    fun hasTotalLost(worldName: String, lost: Int) = unsupportedCheck()
    fun hasPurse(worldName: String, purseName: String) = unsupportedCheck()
}

private val Log = LoggerFactory.getLogger(IntraWorldCheckFactory::class.java)

fun unsupportedCheck(): Check {
    val caller = Thread.currentThread().stackTrace[3]
    Log.debug("unsupportedCheck() generated by ${caller.className}.${caller.methodName}")
    return UnsupportedCheck
}

