plugins {
    id 'azuki.kotlin-conventions'
    id 'azuki.jar-publishing-conventions'
}

dependencies {
    api project(":vdm-animation-api")
    implementation 'org.overturetool.core:interpreter:3.0.2'
    implementation 'org.overturetool.core.annotations:provided:3.0.2'
    implementation libs.slf4j.api
    testImplementation libs.kotlin.test
    testImplementation 'org.mockito.kotlin:mockito-kotlin:3.2.0'
    testImplementation libs.kotlin.reflect
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Overture VDM animator'
                description = 'A programmatic wrapper enabling in-process animation of VDM specifications'
            }
        }
    }
}
